services:
  server:
    image: ayenisholah/bidding-bot-server:latest
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./server/.env
    environment:
      PORT: 3003
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongodb
      - redis
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  client:
    image: ayenisholah/bidding-bot-client:latest
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./client/.env.local
    environment:
      PORT: 3001
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongodb
      - server
      - redis
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    hostname: "redis"
    networks:
      - my_network

volumes:
  mongodb_data:
  redis_data:

networks:
  my_network:
    driver: bridge
