services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./server/.env
    environment:
      PORT: 3003
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongodb
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      PORT: 3001
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongodb
      - server
      - redis

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  redis: # Added Redis service
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
